[tool.poetry]
name = "ipyannotator"
version = "0.2.7"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.1.2"
traitlets = '=4.3.3'
ipycanvas = "^0.5.1"
ipyevents = "^0.8.0"
ipykernel = "^5.3.4"
ipywidgets = "^7.5.1"
jupyterlab = "^2.2.8"
nbdev = "^1.1.0"
twine = "^3.2.0"
wheel = "^0.35.1"

[tool.poetry.dev-dependencies]
nbstripout = "^0.3.9"
RISE = "^5.6"
nbdime = "^2.0.0"
#voila = { git = "https://github.com/voila-dashboards/voila.git", rev = "e23fcca926584a5aa837c3354804aa2d761edda3" }

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

