name: CI

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ipyannotator

jobs:
  ghr_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build ipyannotator image
        run: docker build -t $IMAGE_NAME .

      - name: Log into GCR
        run: echo "${{ secrets.REP_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push ipyannotator image to GCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  test_1:
    name: "Read Notebooks"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - name: Log into GCR
        run: echo "${{ secrets.REP_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from DockerHub
        run: docker pull ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup #  todo (AP): fix img-tag

      - name: Run image in container
        run: docker run --rm ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup /bin/bash -c "poetry run nbdev_read_nbs"

  test_2:
    name: "Check Notebooks Clean"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - name: Log into GCR
        run: echo "${{ secrets.REP_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from DockerHub
        run: docker pull ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup

      - name: Run image in container
        run: docker run --rm ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup /bin/bash -c "./scripts/check_clean_nb.sh"

  test_3:
    name: "Check Notebooks - Lib Diff"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - name: Log into GCR
        run: echo "${{ secrets.REP_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from DockerHub
        run: docker pull ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup

      - name: Run image in container
        run: docker run --rm ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup /bin/bash -c "./scripts/check_lib_diff.sh"

  test_4:
    name: "Run Notebooks tests"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - name: Log into GCR
        run: echo "${{ secrets.REP_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from DockerHub
        run: docker pull ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup

      - name: Run image in container
        run: docker run --rm ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup /bin/bash -c "./scripts/test_nb.sh"

  release_1:
    name: "Build whls"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - name: Log into GCR
        run: echo "${{ secrets.REP_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from DockerHub
        run: docker pull ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup

      - name: Run image in container
        run: docker run --rm -v $(pwd)/dist:/app/dist ghcr.io/alexjoz/ipyannotator/ipyannotator:github-setup /bin/bash -c "./scripts/build_whl.sh"

      - name: Archive whls
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/**.whl
