name: CI

on:
#  push:
  workflow_dispatch:

jobs:
  ghr_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        uses: ./.github/actions/docker-image-tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REP_PAT }}

      -  name: Build and push
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./Dockerfile
#          push: ${{ github.event_name != 'pull_request' }}
           push: true
           tags: ${{ steps.prep.outputs.tag }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: mode=max,type=local,dest=/tmp/.buildx-cache


  read_notebooks:
    name: "Read Notebooks"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        uses: ./.github/actions/docker-image-tag

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REP_PAT }}

      - name: Pull image from DockerHub
        run: docker pull ${{ steps.prep.outputs.tag }}

      - name: Run image in container
        run: docker run --rm ${{ steps.prep.outputs.tag }} /bin/bash -c "poetry run nbdev_read_nbs"

  check_notebooks_clean:
    name: "Check Notebooks Clean"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        uses: ./.github/actions/docker-image-tag

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REP_PAT }}

      - name: Pull image from GitHub Container Registry
        run: docker pull ${{ steps.prep.outputs.tag }}

      - name: Run image [Check Notebooks Clean]
        run: docker run --rm ${{ steps.prep.outputs.tag }} /bin/bash -c "./scripts/check_clean_nb.sh"

  check_diff_lib_nbs:
    name: "Check Notebooks - Lib Diff"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        uses: ./.github/actions/docker-image-tag

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REP_PAT }}

      - name: Pull image from GitHub Container Registry
        run: docker pull ${{ steps.prep.outputs.tag }}

      - name: Run image [Check lib diff]
        run: docker run --rm ${{ steps.prep.outputs.tag }} /bin/bash -c "./scripts/check_lib_diff.sh"

  run_tests:
    name: "Run Notebooks tests"
    runs-on: ubuntu-latest
    needs: ghr_push

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        uses: ./.github/actions/docker-image-tag

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REP_PAT }}

      - name: Pull image from GitHub Container Registry
        run: docker pull ${{ steps.prep.outputs.tag }}

      - name: Run image [Execute nb tests]
        run: docker run --rm ${{ steps.prep.outputs.tag }} /bin/bash -c "./scripts/test_nb.sh"
